"""
run_sim.py — render the netlist template, run ngspice, check assertions, plot.

Usage:
  python run_sim.py --all          # run every scenario, write results/RESULTS.md
  python run_sim.py A_nominal_40C  # run one scenario
  python run_sim.py --list
"""
import argparse
import subprocess
import sys
from pathlib import Path

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

sys.path.insert(0, str(Path(__file__).parent.parent))  # scenarios.py is shared with ../ltspice
from scenarios import SCENARIOS, V_START, V_FAN_MAX

NGSPICE = r"E:\Catalin\Work\Electronics\NGSpice_46\bin\ngspice_con.exe"
SIM_DIR = Path(__file__).parent
RESULTS_DIR = SIM_DIR / "results"
TEMPLATE = SIM_DIR / "fan_ctrl.cir.tmpl"
COLS = ["sweep", "vin", "t", "v5", "vref", "vadj", "vfan", "i317", "ifan"]


def render(sc: dict, out_csv: Path) -> str:
    text = TEMPLATE.read_text(encoding="utf-8")
    subs = dict(sc["subs"], NAME=sc["name"], ANALYSIS=sc["analysis"],
                MODELSLIB=(SIM_DIR / "models.lib").as_posix(), OUTCSV=out_csv.as_posix())
    for k, v in subs.items():
        text = text.replace("{{" + k + "}}", str(v))
    if "{{" in text:
        raise ValueError(f"unresolved placeholder in {sc['name']}")
    return text


def run(sc: dict) -> tuple[bool, list[str]]:
    out = RESULTS_DIR / sc["name"]
    out.mkdir(parents=True, exist_ok=True)
    csv = out / "out.csv"
    cir = out / "sim.cir"
    cir.write_text(render(sc, csv), encoding="utf-8")

    r = subprocess.run([NGSPICE, "-b", str(cir)], capture_output=True, text=True,
                       timeout=300, cwd=str(out))
    (out / "ngspice.log").write_text(r.stdout + r.stderr, encoding="utf-8")
    if r.returncode != 0 or not csv.exists():
        return False, [f"ngspice failed (exit {r.returncode}), see ngspice.log"]

    df = pd.read_csv(csv, sep=r"\s+", skiprows=1, header=None, names=COLS)
    results = sc["assertions"](df)
    plot(df, sc, out / "plot.png")

    lines = [f"{'PASS' if ok else 'FAIL'}  {msg}" for ok, msg in results]
    (out / "summary.txt").write_text(f"{sc['name']}: {sc['desc']}\n" + "\n".join(lines) + "\n",
                                     encoding="utf-8")
    return all(ok for ok, _ in results), lines


def plot(df: pd.DataFrame, sc: dict, path: Path) -> None:
    x = df["sweep"]
    xlabel = {"dc_temp": "Temperature (°C)", "dc_vin": "V_in (V)", "tran": "Time (ms)"}[sc["kind"]]
    if sc["kind"] == "tran":
        x = x * 1e3

    fig, axes = plt.subplots(2, 1, figsize=(9, 7), sharex=True)
    fig.suptitle(f"{sc['name']} — {sc['desc']}", fontsize=10)

    ax = axes[0]
    ax.plot(x, df["vfan"], label="V_fan", color="tab:red", lw=2)
    ax.plot(x, df["vadj"], label="V_adj (U2A out)", color="tab:blue")
    ax.plot(x, df["vref"], label="V_ref (U2B out)", color="tab:green")
    if sc["kind"] == "tran":
        ax.plot(x, df["v5"], label="+5 V rail", color="tab:gray", ls="--")
    ax.axhline(V_START, color="k", ls=":", lw=0.8, label=f"fan start ≈ {V_START} V")
    ax.axhline(V_FAN_MAX, color="k", ls="--", lw=0.8, label=f"limit {V_FAN_MAX} V")
    ax.set_ylabel("Voltage (V)")
    ax.legend(fontsize=8, loc="upper left")
    ax.grid(alpha=0.3)

    ax = axes[1]
    ax.plot(x, df["ifan"] * 1e3, label="I_fan (mA)", color="tab:red")
    p = (df["vin"] - df["vfan"]) * df["i317"]
    ax2 = ax.twinx()
    ax2.plot(x, p, label="P(U1 LM317) (W)", color="tab:purple", ls="--")
    ax2.set_ylabel("Power (W)")
    ax.set_ylabel("Current (mA)")
    ax.set_xlabel(xlabel)
    h1, l1 = ax.get_legend_handles_labels()
    h2, l2 = ax2.get_legend_handles_labels()
    ax.legend(h1 + h2, l1 + l2, fontsize=8, loc="upper left")
    ax.grid(alpha=0.3)

    plt.tight_layout()
    plt.savefig(path, dpi=110)
    plt.close(fig)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("names", nargs="*")
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--list", action="store_true")
    args = ap.parse_args()

    if args.list:
        for s in SCENARIOS:
            print(f"{s['name']:24s} {s['desc']}")
        return

    chosen = SCENARIOS if args.all else [s for s in SCENARIOS if s["name"] in args.names]
    if not chosen:
        ap.error("give scenario names, --all or --list")

    report = ["# Simulation results\n", "> Generated by `run_sim.py --all`.\n",
              "| Scenario | Description | Result |", "|---|---|---|"]
    details = []
    for s in chosen:
        ok, lines = run(s)
        print(f"{'PASS' if ok else 'FAIL'}  {s['name']}")
        for ln in lines:
            print(f"      {ln}")
        report.append(f"| [{s['name']}]({s['name']}/plot.png) | {s['desc']} | {'✅ PASS' if ok else '❌ FAIL'} |")
        details += [f"\n### {s['name']}\n", *[f"- {ln}" for ln in lines]]

    if args.all:
        (RESULTS_DIR / "RESULTS.md").write_text("\n".join(report + ["\n## Details"] + details) + "\n",
                                                encoding="utf-8")


if __name__ == "__main__":
    main()
